upgrade log throwable
reactivegroup/capa-aws pull request #74
Opened 2021-12-20 09:38 UTC by dgzpg

# Description

upgrade log throwable

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2021-12-21 09:47 UTC, kevinten10 requested changes

2021-12-21 09:47 UTC, kevinten10 commented on capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/handle/MessageSender.java
> +            throwable.printStackTrace();
can you explain the usage here

2021-12-21 09:47 UTC, kevinten10 commented on capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/LogAppendManager.java
> +            //put logs by agent
// 后面接空格

2021-12-21 09:47 UTC, kevinten10 commented on capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/LogAppendManager.java
> +            throwable.printStackTrace(pw);
能否把printStackTrace这种用法统一包装起来，这样后续也好替换

2021-12-21 09:47 UTC, kevinten10 commented on capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/LogAppendManager.java
> +        }catch (Throwable e){
这里catch的目的是？

2021-12-21 09:47 UTC, kevinten10 commented on capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchMetricsExporter.java
> +            log.warn("Fail to export metrics.", e);
中间件内部的异常日志，最好统一加个前缀，例如：[Capa.Log]

2021-12-22 10:25 UTC, dgzpg commented on capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/LogAppendManager.java
> +        }catch (Throwable e){
这里只是增强的加一下tag，不强依赖这些tag，如果如appId获取失败不会导致整个日志输出失败。

2021-12-22 10:25 UTC, dgzpg commented on capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchMetricsExporter.java
> +            log.warn("Fail to export metrics.", e);
@JasmineJ1230

2021-12-22 10:26 UTC, dgzpg commented on capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchMetricsExporter.java
> +            log.warn("Fail to export metrics.", e);
@JasmineJ1230

2021-12-22 10:26 UTC, dgzpg commented on capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/handle/MessageSender.java
> +            throwable.printStackTrace();
能够输出异常日志

2021-12-22 10:26 UTC, dgzpg commented on capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/LogAppendManager.java
> +            //put logs by agent
好的，我改下

2021-12-22 11:37 UTC, dgzpg commented on capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/LogAppendManager.java
> +            throwable.printStackTrace(pw);
可以考虑像这种异常日志使用一套规范去打印，如日志信息里面加上日志错误级别。

2022-01-05 08:42 UTC, merged